#!/usr/bin/env node
/**
 * build-tokens.mjs — closes #321
 *
 * Reads src/tokens.json and regenerates src/tokens.css.
 * Run via: node scripts/build-tokens.mjs
 *          or npm run build:tokens
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const tokensPath = resolve(__dirname, "../src/tokens.json");
const outputPath = resolve(__dirname, "../src/tokens.css");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

/** Convert camelCase to kebab-case */
function toKebab(str) {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`);
}

const lines = [];

lines.push("/* =============================================================");
lines.push("   Design Tokens — auto-generated by scripts/build-tokens.mjs");
lines.push("   DO NOT EDIT MANUALLY — edit src/tokens.json instead.");
lines.push("   ============================================================= */");
lines.push("");
lines.push(":root {");

// ── Colors ─────────────────────────────────────────────────────────────────
lines.push("  /* ── Color: Primary (purple/indigo) ── */");
for (const [scale, value] of Object.entries(tokens.color.primary)) {
  lines.push(`  --color-primary-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Color: Secondary (slate) ── */");
for (const [scale, value] of Object.entries(tokens.color.secondary)) {
  lines.push(`  --color-secondary-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Color: Accent (amber) ── */");
for (const [scale, value] of Object.entries(tokens.color.accent)) {
  lines.push(`  --color-accent-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Color: Success ── */");
for (const [scale, value] of Object.entries(tokens.color.success)) {
  lines.push(`  --color-success-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Color: Warning ── */");
for (const [scale, value] of Object.entries(tokens.color.warning)) {
  lines.push(`  --color-warning-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Color: Error ── */");
for (const [scale, value] of Object.entries(tokens.color.error)) {
  lines.push(`  --color-error-${scale}: ${value};`);
}
lines.push("");

lines.push("  /* ── Semantic surface tokens (dark-mode defaults) ── */");
for (const [key, value] of Object.entries(tokens.color.semantic)) {
  lines.push(`  --color-${key}: ${value};`);
}
lines.push("");

lines.push("  /* shorthand aliases kept for backward compat */");
lines.push("  --color-primary:      var(--color-primary-500);");
lines.push("  --color-primary-dark: var(--color-primary-600);");
lines.push("  --color-complete:     var(--color-success-500);");
lines.push("  --color-revoke:       var(--color-error-500);");
lines.push("");

// ── Typography ──────────────────────────────────────────────────────────────
lines.push("  /* ── Typography scale ── */");
lines.push(`  --font-sans:  ${tokens.typography.fontFamily.sans};`);
lines.push(`  --font-mono:  ${tokens.typography.fontFamily.mono};`);
lines.push("");

const sizeComments = { xs: "12px", sm: "13px", base: "14px", md: "16px", lg: "18px", xl: "20px", "2xl": "24px", "3xl": "30px", "4xl": "36px" };
for (const [key, value] of Object.entries(tokens.typography.fontSize)) {
  const comment = sizeComments[key] ? `  /* ${sizeComments[key]} */` : "";
  lines.push(`  --text-${key}: ${value};${comment}`);
}
lines.push("");

for (const [key, value] of Object.entries(tokens.typography.lineHeight)) {
  lines.push(`  --leading-${key}: ${value};`);
}
lines.push("");

for (const [key, value] of Object.entries(tokens.typography.fontWeight)) {
  lines.push(`  --font-${key}: ${value};`);
}
lines.push("");

// ── Spacing ─────────────────────────────────────────────────────────────────
lines.push("  /* ── Spacing scale (4px base grid) ── */");
for (const [key, value] of Object.entries(tokens.spacing)) {
  lines.push(`  --space-${key}: ${value};`);
}
lines.push("");

// ── Border radius ────────────────────────────────────────────────────────────
lines.push("  /* ── Border radius ── */");
for (const [key, value] of Object.entries(tokens.borderRadius)) {
  const name = key === "base" ? "--radius" : `--radius-${key}`;
  lines.push(`  ${name}: ${value};`);
}
lines.push("");

// ── Shadows ──────────────────────────────────────────────────────────────────
lines.push("  /* ── Shadows ── */");
for (const [key, value] of Object.entries(tokens.shadow)) {
  const name = key === "base" ? "--shadow" : `--shadow-${key}`;
  lines.push(`  ${name}: ${value};`);
}
lines.push("");

// ── Elevation ────────────────────────────────────────────────────────────────
lines.push("  /* ── Elevation (box-shadow scale) — closes #321 ── */");
for (const [key, value] of Object.entries(tokens.elevation)) {
  lines.push(`  --elevation-${key}: ${value};`);
}
lines.push("");

// ── Transitions ──────────────────────────────────────────────────────────────
lines.push("  /* ── Transitions ── */");
for (const [key, value] of Object.entries(tokens.transition)) {
  lines.push(`  --transition-${toKebab(key)}: ${value};`);
}

lines.push("}");
lines.push("");
lines.push("@media (prefers-color-scheme: light) {");
lines.push("  :root {");
lines.push("    --color-bg:      #f8fafc;");
lines.push("    --color-surface: #ffffff;");
lines.push("    --color-border:  #e2e8f0;");
lines.push("    --color-text:    #0f172a;");
lines.push("    --color-muted:   #64748b;");
lines.push("  }");
lines.push("}");
lines.push("");

writeFileSync(outputPath, lines.join("\n"), "utf8");
console.log("✓  Generated src/tokens.css");
